import {
  AdminPanelSettings,
  Person,
  PersonAdd,
  Settings,
  LocalHospital,
  MedicalServices,
  Vaccines,
  EventAvailable,
  ExpandMore,
  ExpandLess,
  Sick,
  StackedBarChart,
  SignalCellular0Bar,
  SignalCellularAlt,
  SignalCellularAlt1Bar,
  PriceCheck,
  Warehouse,
  AddBusiness,
  Healing,
  QueryStats,
  LockPerson,
  Functions,
  Category,
  Portrait,
  MeetingRoom,
  MonetizationOn,
  MedicalInformation,
  Store,
  Paid,
} from "@mui/icons-material";
import { ListItemAvatar } from "@mui/material";

export const items = [
  {
    id: "ADM",
    name: "Admin",
    icon: <AdminPanelSettings />,
    role:[],
    subMenu: [
      {
        id: "TKNV",
        name: "Tài khoản/nhân viên",
        icon: <PersonAdd />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "NQ",
        name: "Nhóm quyền",
        icon: <LockPerson />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "FCN",
        name: "Chức năng",
        icon: <Functions />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "CDT",
        name: "Cài đặt",
        icon: <Settings />,
        subMenu: [],
        role:[]
      },
    ],
  },
  {
    id: "DMC",
    name: "Danh mục",
    icon: <Category />,
    role: ["ADMIN","DRUG_DEALER","TEST"],
    subMenu: [
      {
        id: "BNN",
        name: "Bệnh nhân",
        icon: <Portrait />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "PGB",
        name: "Phòng ban",
        icon: <MeetingRoom />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "NMSP",
        name: "Nhóm sản phẩm",
        icon: <Vaccines />,
        subMenu: [],
        role: ["ADMIN","DRUG_DEALER"],
      },
      {
        id: "PRD",
        name: "Sản phẩm",
        icon: <Vaccines />,
        subMenu: [],
        role: ["ADMIN","DRUG_DEALER"],
      },
      {
        id: "DVKM",
        name: "Dịch vụ khám",
        icon: <MedicalInformation />,
        subMenu: [],
        role: ["ADMIN","TEST"],
      },
      {
        id: "NCCDV",
        name: "Nhà cung cấp",
        icon: <Store />,
        subMenu: [],
        role: ["ADMIN","DRUG_DEALER"],
      },
    ],
  },
  {
    id: "LTN",
    name: "Lễ tân",
    icon: <Person />,
    role: ["RECEPTIONIST"],
    subMenu: [
      {
        id: "TDBN",
        name: "Tiếp đón bệnh nhân",
        icon: <Sick />,
        subMenu: [],
        role: ["RECEPTIONIST"],
      },
      {
        id: "LHK",
        name: "Lịch hẹn khám",
        icon: <EventAvailable />,
        subMenu: [],
        role: ["RECEPTIONIST"],
      },
    ],
  },
  {
    id: "HMB",
    name: "Khám bệnh",
    icon: <LocalHospital />,
    subMenu: [],
    role: ["DOCTOR", "NURSE"],
  },
  {
    id: "DV",
    name: "Dịch vụ",
    icon: <MedicalServices />,
    role: ["TEST"],
    subMenu: [
      {
        id: "DSDV",
        name: "Danh sách dịch vụ",
        icon: <EventAvailable />,
        subMenu: [],
        role: ["TEST"],
      },
      {
        id: "QLTT",
        name: "Quản lý tập tin",
        icon: <EventAvailable />,
        subMenu: [],
        role: ["TEST"],
      },
    ],
  },
  {
    id: "SP",
    name: "Sản phẩm",
    icon: <Vaccines />,
    role: ["ADMIN","DRUG_DEALER"],
    subMenu: [
      {
        id: "CHGB",
        name: "Cấu hình giá bán",
        icon: <PriceCheck />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "TNK",
        name: "Tồn kho",
        icon: <Warehouse />,
        subMenu: [],
        role: ["ADMIN","DRUG_DEALER"],
      },
      {
        id: "NSP",
        name: "Nhập sản phẩm",
        icon: <AddBusiness />,
        subMenu: [],
        role: ["ADMIN","DRUG_DEALER"],
      },
      {
        id: "DNT",
        name: "Đơn thuốc",
        icon: <Healing />,
        subMenu: [],
        role: ["DRUG_DEALER"],
      },
    ],
  },
  {
    id: "TCI",
    name: "Thu chi",
    icon: <MonetizationOn />,
    role: ["RECEPTIONIST"],
    subMenu: [
      {
        id: "TTDV",
        name: "Thanh toán dịch vụ",
        icon: <PriceCheck />,
        subMenu: [],
        role: ["RECEPTIONIST"],
      },
      // {
      //   id: "THLK",
      //   name: "Tổng hợp loại khám",
      //   icon: <SignalCellularAlt />,
      //   subMenu: [],
      // },
      // {
      //   id: "THDV",
      //   name: "Tổng hợp dịch vụ",
      //   icon: <SignalCellularAlt />,
      //   subMenu: [],
      // },
      // {
      //   id: "THDT",
      //   name: "Tổng hợp doanh thu",
      //   icon: <QueryStats />,
      //   subMenu: [],
      // },
    ],
  },
  {
    id: "BC",
    name: "Báo cáo",
    icon: <StackedBarChart />,
    role: ["ADMIN"],
    subMenu: [
      {
        id: "THDT",
        name: "Tổng hợp doanh thu",
        icon: <QueryStats />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "CTLK",
        name: "Chi tiết loại Khám",
        icon: <SignalCellularAlt />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "THLK",
        name: "Tổng hợp loại khám",
        icon: <SignalCellularAlt />,
        subMenu: [],
        role: ["ADMIN"],
      },
      {
        id: "THDV",
        name: "Tổng hợp dịch vụ",
        icon: <SignalCellularAlt />,
        subMenu: [],
        role: ["ADMIN"],
      },
    ],
  },
];

export const itemMap = new Map([
  ["TKNV", "ADM"],
  ["CDT", "ADM"],
  ["FCN", "ADM"],
  ["NQ", "ADM"],

  ["BNN", "DMC"],
  ["PGB", "DMC"],
  ["NMSP", "DMC"],
  ["PRD", "DMC"],
  ["DVKM", "DMC"],
  ["NCCDV", "DMC"],

  ["TDBN", "LTN"],
  ["LHK", "LTN"],

  ["CHGB", "SP"],
  ["TNK", "SP"],
  ["NSP", "SP"],
  ["DNT", "SP"],

  ["QLTT", "DV"],
  ["DSDV", "DV"],

  ["CTLK", "BC"],
  ["THLK", "BC"],
  ["THDV", "BC"],
  ["THDT", "BC"],

  ["TTDV","TCI"],
]);
